INSERT INTO EXPENSE_CATEGORY (ID, NAME) VALUES (1, 'Cat');
INSERT INTO EXPENSE_CATEGORY (ID, NAME) VALUES (2, 'Home');
INSERT INTO EXPENSE_CATEGORY (ID, NAME) VALUES (3, 'Clothes');

INSERT INTO EXPENSE (AMOUNT, NAME, CATEGORY_ID) VALUES (10.99, 'Catnip', 1);
INSERT INTO EXPENSE (AMOUNT, NAME, CATEGORY_ID) VALUES (13.46, 'Bread and cheese', 4);
INSERT INTO EXPENSE (AMOUNT, NAME, CATEGORY_ID) VALUES (4.99, 'Chocolate', 4);
INSERT INTO EXPENSE (AMOUNT, NAME, CATEGORY_ID) VALUES (89.99, 'Candles', 2);
INSERT INTO EXPENSE (AMOUNT, NAME, CATEGORY_ID) VALUES (54.99, 'Winter gloves', 3);