INSERT INTO EXPENSE_CATEGORY (ID, NAME) VALUES (1, 'Cat');
INSERT INTO EXPENSE_CATEGORY (ID, NAME) VALUES (2, 'Home');
INSERT INTO EXPENSE_CATEGORY (ID, NAME) VALUES (3, 'Clothes');
INSERT INTO EXPENSE_CATEGORY (ID, NAME) VALUES (4, 'Food');

INSERT INTO EXPENSE (ID, AMOUNT, NAME, CATEGORY_ID) VALUES (1, 10.99, 'Catnip', 1);
INSERT INTO EXPENSE (ID, AMOUNT, NAME, CATEGORY_ID) VALUES (2, 13.46, 'Bread and cheese', 4);
INSERT INTO EXPENSE (ID, AMOUNT, NAME, CATEGORY_ID) VALUES (3, 4.99, 'Chocolate', 4);
INSERT INTO EXPENSE (ID, AMOUNT, NAME, CATEGORY_ID) VALUES (4, 89.99, 'Candles', 2);
INSERT INTO EXPENSE (ID, AMOUNT, NAME, CATEGORY_ID) VALUES (5, 54.99, 'Winter gloves', 3);